server:
  port: 80
  session-timeout: 1000000 #用户回话session过期时间，以秒为单位
  tomcat:
    uri-encoding: "UTF-8" #配置Tomcat编码，默认为UTF-8
    compression: "on"
logging:
  config: "classpath:log4j2.yml"
system-config:
  txtPath: "E://test/txt"